[package]
name = "auto_civitai_rs"
version = "0.1.0"
edition = "2021"
description = "Civitai with Rust"
repository = "https://github.com/alpertunga-bile/auto_civitai_rs"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = "0.46.0"
reqwest = "0.12.12"
serde = {version = "1.0.217", features = ["derive"]}
serde_json = "1.0.138"

[profile.release]
lto=true
